---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        # process management
        - htop
        # terminal multiplexer
        - tmux
        # system information
        - neofetch
        # fun
        - cmatrix
        # podman
